#!/bin/sh
echo “Adding folders...”

mkdir js;
mkdir css;
mkdir scss;
echo "Folders complete."

echo "Adding files..."
printf "<!DOCTYPE>\n<html>\n<head>\n<script></script>\n</head>\n\n<body></body>\n</html>" > index.html;
printf "/* jslint browser: true */" > js/app.js;
printf "@import \"bourbon/bourbon\";\n@import \"neat/neat\";" > scss/index.scss;
echo "Files complete."

echo "Installing bourbon/neat..."
cd scss;
bourbon install;
neat install;
cd ..
echo "Installing Gulp w/ npm..."
npm install gulp
echo "Gulp Installed."

echo "Diamond 100% complete."
