#!/bin/sh
echo “Adding folders...”

mkdir js;
mkdir scss;
echo "Folders complete."

echo "Adding files..."
printf "<!DOCTYPE html>\n<html>\n<head>\n<script></script>\n</head>\n\n<body></body>\n</html>" > index.html;
printf "/* jslint browser: true */" > js/app.js;
printf "@import \"bourbon/bourbon\";\n@import \"neat/neat\";" > scss/index.scss;
echo "Files complete."

printf "var gulp = require('gulp');"

#Install different project specific programs below.

echo "Installing bourbon/neat..."
cd scss;
bourbon install;
neat install;
cd ..
echo "Installing Gulp w/ npm..."
npm install --save-dev gulp
echo "Gulp Installed."

echo "Intstalling Gulp-Browserify..."
npm install gulp-browserify
echo "Gulp-browserify installed."

echo "Diamond 100% complete."
